apiVersion: v1
kind: Service
metadata:
  name: arithmetic-service
spec:
  type: NodePort
  selector:
    app: arithmetic-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007